services:
  postgres:
    volumes:
      - type: bind
        source: "${DATA_STORAGE_ROOT}/postgres"
        target: /var/lib/postgresql/data
        bind:
          create_host_path: false

  minio:
    volumes:
      - type: bind
        source: "${DATA_STORAGE_ROOT}/minio"
        target: /data
        bind:
          create_host_path: false
